apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: "loki"
        tags: ["job", "container"]
        mappedTags: [{ key: "service.name", value: "job" }]
        mapTagNamesEnabled: false
      tracesToMetrics:
        datasourceUid: "prometheus"
        tags: [{ key: "service.name" }, { key: "span.name" }]
        queries:
          - name: "Duration"
            query: "sum(rate(tempo_spanmetrics_latency_bucket{$$__tags__}[$$__rate_interval__]))"
          - name: "Count"
            query: "sum(rate(tempo_spanmetrics_calls_total{$$__tags__}[$$__rate_interval__]))"
      serviceMap:
        datasourceUid: "prometheus"
    uid: tempo
    editable: false

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: "tempo"
        tags: ["job", "container"]
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: false
    uid: loki
    editable: false
